### ISSUE TITLE
pip install -r requirements.txt error

### ISSUE THREAD

**Issue by johnfelipe** [dasoto/skincancer#6]
root@dos-ubuntu-s-8vcpu-16gb-nyc1-01:~/hub-skin-cancer# pip install -r requirements.txt
    Collecting h5py<3.0.0
      Downloading h5py-2.10.0-cp38-cp38-manylinux1_x86_64.whl (2.9 MB)
         |████████████████████████████████| 2.9 MB 18.1 MB/s
    ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from -r requirements.txt (line 2)) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0)
    ERROR: No matching distribution found for tensorflow==1.15 (from -r requirements.txt (line 2))

ubuntu 20.04 from scratch

**Comment by johnfelipe** [comment]
i change to 2.2 tensorflow, but show me this when want to deploy gradio web ui

    Traceback (most recent call last):
      File "run-gradio.py", line 8, in <module>
        model = load_model("./models/mymodel-2.h5")
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
        return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 177, in load_model_from_hdf5
        model = model_config_lib.model_from_config(model_config,
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
        return deserialize(config, custom_objects=custom_objects)
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/layers/serialization.py", line 105, in deserialize
        return deserialize_keras_object(
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 361, in deserialize_keras_object
        (cls, cls_config) = class_and_config_for_serialized_keras_object(
      File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 325, in class_and_config_for_serialized_keras_object
        for key, item in cls_config.items():
    AttributeError: 'list' object has no attribute 'items'
